jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/325403088135/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider'
          service_account: 'github-action-mrflesher@mrflesher.iam.gserviceaccount.com'
