name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload build folder
      uses: actions/upload-artifact@v3
      with:
        name: npm-build-artifact
        path: ./build
    - run: ls -la
  
  upload:
    # Allow the job to fetch a GitHub ID token
    needs: build
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:     
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: npm-build-artifact

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{secrets.SERVICE_ACCOUNT}}'
          
      - run: ls -la
      
      - name: Upload to GCP Bucket
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '.'
          destination: 'mrflesher'
          
  
